
exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('photos').del()
  .then(() => {
    // Inserts seed entries
    return knex('photos').insert([
    {id: 1, gallery_id: 3, src: '/images/harbour-bridge-sydney.jpg', location: 'Australia', category: 'cityscape', favourite: 'no', width: 4, height: 2},
    {id: 2, gallery_id: 1, src: '/images/mclaren-falls.jpg', location: 'New Zealand', category: 'landscape', favourite: 'yes', width: 4, height: 2},
    {id: 3, gallery_id: 1, src: '/images/white-island.jpg', location: 'New Zealand', category: 'landscape', favourite: 'no', width: 4, height: 2},
    {id: 4, gallery_id: 3, src: '/images/auckland-new-years.jpg', location: 'New Zealand', category: 'cityscape', favourite: 'yes', width: 4, height: 3},
    {id: 5, gallery_id: 3, src: '/images/harbour-bridge-sydney1.jpg', location: 'Australia', category: 'cityscape', favourite: 'no', width: 4, height: 2},
    {id: 6, gallery_id: 3, src: '/images/darling-harbour-fireworks.jpg', location: 'Australia', category: 'cityscape', favourite: 'no', width: 3, height: 4},
    {id: 8, gallery_id: 2, src: '/images/muriwai-astro.jpg', location: 'New Zealand', category: 'astro', favourite: 'yes', width: 4, height: 2},
    {id: 9, gallery_id: 1, src: '/images/anawhata.jpg', location: 'New Zealand', category: 'landscape', favourite: 'no', width: 4, height: 3},
    {id: 10, gallery_id: 2, src: '/images/bethells-milkyway.jpg', location: 'New Zealand', category: 'astro', favourite: 'no', width: 3, height: 4},
    {id: 11, gallery_id: 2, src: '/images/bethells.jpg', location: 'New Zealand', category: 'astro', favourite: 'no', width: 3, height: 4},
    {id: 12, gallery_id: 2, src: '/images/pakiri.jpg', location: 'New Zealand', category: 'astro', favourite: 'no', width: 3, height: 4},
    {id: 13, gallery_id: 2, src: '/images/whatipu-river.jpg', location: 'New Zealand', category: 'astro', favourite: 'no', width: 3, height: 4},
    {id: 14, gallery_id: 2, src: '/images/whatipu-milkyway.jpg', location: 'New Zealand', category: 'astro', favourite: 'no', width: 4, height: 2},
    {id: 16, gallery_id: 3, src: '/images/morning-bridge.jpg', location: 'Australia', category: 'cityscape', favourite: 'no', width: 4, height: 3},
    {id: 17, gallery_id: 3, src: '/images/darling-harbour-in-pink.jpg', location: 'Australia', category: 'cityscape', favourite: 'yes', width: 4, height: 3},
    {id: 18, gallery_id: 3, src: '/images/rainy-gold-coast.jpg', location: 'Australia', category: 'cityscape', favourite: 'no', width: 4, height: 3},
    {id: 19, gallery_id: 2, src: '/images/fields-of-light-tree.jpg', location: 'Australia', category: 'astro', favourite: 'no', width: 3, height: 4},
    {id: 20, gallery_id: 2, src: '/images/fields-of-light.jpg', location: 'Australia', category: 'astro', favourite: 'no', width: 3, height: 4},
    {id: 21, gallery_id: 4, src: '/images/kings-canyon-tree.jpg', location: 'Australia', category: 'landscape', favourite: 'no', width: 3, height: 4},
    {id: 22, gallery_id: 4, src: '/images/kings-canyon.jpg', location: 'Australia', category: 'landscape', favourite: 'no', width: 3, height: 4},
    {id: 23, gallery_id: 3, src: '/images/early-morning-bridge.jpg', location: 'Australia', category: 'cityscape', favourite: 'no', width: 4, height: 2},
    {id: 25, gallery_id: 3, src: '/images/natural-fireworks.jpg', location: 'Australia', category: 'cityscape', favourite: 'no', width: 4, height: 1},
    {id: 26, gallery_id: 6, src: '/images/sydney-cbd-bw.jpg', location: 'Australia', category: 'landscape', favourite: 'no', width: 3, height: 4},
    {id: 27, gallery_id: 3, src: '/images/gold-coast-view.jpg', location: 'Australia', category: 'cityscape', favourite: 'no', width: 4, height: 3},
    {id: 28, gallery_id: 5, src: '/images/rainbow-parikeet.jpg', location: 'Australia', category: 'landscape', favourite: 'no', width: 4, height: 3},
    {id: 29, gallery_id: 3, src: '/images/sydney-harbour.jpg', location: 'Australia', category: 'cityscape', favourite: 'no', width: 4, height: 3},
    {id: 31, gallery_id: 3, src: '/images/smokey-gold-coast-sunrise.jpg', location: 'Australia', category: 'cityscape', favourite: 'no', width: 4, height: 3},
    {id: 32, gallery_id: 3, src: '/images/pink-gold-coast-sunset.jpg', location: 'Australia', category: 'cityscape', favourite: 'no', width: 3, height: 4},
    {id: 33, gallery_id: 3, src: '/images/sails.jpg', location: 'Australia', category: 'cityscape', favourite: 'yes', width: 4, height: 4},
    {id: 34, gallery_id: 3, src: '/images/sydney-park-view.jpg', location: 'Australia', category: 'cityscape', favourite: 'no', width: 4, height: 3},
    {id: 35, gallery_id: 3, src: '/images/gold-coast-storm.jpg', location: 'Australia', category: 'cityscape', favourite: 'no', width: 3, height: 4},
    {id: 37, gallery_id: 3, src: '/images/storm-over-sydney.jpg', location: 'Australia', category: 'cityscape', favourite: 'no', width: 4, height: 3},
    {id: 38, gallery_id: 3, src: '/images/smokey-sunrise.jpg', location: 'Australia', category: 'cityscape', favourite: 'no', width: 4, height: 3},
    {id: 39, gallery_id: 3, src: '/images/gold-coast-blues.jpg', location: 'Australia', category: 'cityscape', favourite: 'no', width: 3, height: 4},
    {id: 41, gallery_id: 3, src: '/images/auckland-pink.jpg', location: 'New Zealand', category: 'cityscape', favourite: 'no', width: 4, height: 3},
    {id: 43, gallery_id: 3, src: '/images/fireworks-in-auckland.jpg', location: 'New Zealand', category: 'cityscape', favourite: 'no', width: 4, height: 3},
    {id: 44, gallery_id: 3, src: '/images/melbourne-moon.jpg', location: 'Australia', category: 'cityscape', favourite: 'no', width: 4, height: 3},
    {id: 45, gallery_id: 3, src: '/images/mt-eden.jpg', location: 'New Zealand', category: 'cityscape', favourite: 'no', width: 4, height: 3},
    {id: 46, gallery_id: 3, src: '/images/spaghetti-junction.jpg', location: 'New Zealand', category: 'cityscape', favourite: 'no', width: 4, height: 3},
    {id: 47, gallery_id: 3, src: '/images/wellington-CBD.jpg', location: 'New Zealand', category: 'cityscape', favourite: 'no', width: 4, height: 3},
    {id: 48, gallery_id: 3, src: '/images/westhaven.jpg', location: 'New Zealand', category: 'cityscape', favourite: 'no', width: 4, height: 3},
    {id: 49, gallery_id: 2, src: '/images/barrenjoey-milkyway.jpg', location: 'Australia', category: 'astro', favourite: 'no', width: 3, height: 4},
    {id: 50, gallery_id: 2, src: '/images/beach-and-milkyway.jpg', location: 'Australia', category: 'astro', favourite: 'no', width: 3, height: 4},
    {id: 51, gallery_id: 2, src: '/images/palm-beach-milkyway-panorama.jpg', location: 'Australia', category: 'astro', favourite: 'no', width: 4, height: 2},
    {id: 52, gallery_id: 2, src: '/images/palm-beach-milkyway.jpg', location: 'Australia', category: 'astro', favourite: 'no', width: 3, height: 4},
    {id: 53, gallery_id: 4, src: '/images/pioneer-lookout.jpg', location: 'Australia', category: 'landscape', favourite: 'yes', width: 4, height: 3},
    {id: 54, gallery_id: 2, src: '/images/shoalhaven-milkyway.jpg', location: 'Australia', category: 'astro', favourite: 'no', width: 3, height: 4},
    {id: 55, gallery_id: 5, src: '/images/spiderwasp-and-huntsman.jpg', location: 'Australia', category: 'wildlife', favourite: 'no', width: 4, height: 3},
    {id: 56, gallery_id: 5, src: '/images/grey-headed-flying-fox.jpg', location: 'Australia', category: 'wildlife', favourite: 'no', width: 3, height: 4},
    {id: 57, gallery_id: 5, src: '/images/juvenile-humpback.jpg', location: 'Australia', category: 'wildlife', favourite: 'no', width: 4, height: 3},
    {id: 58, gallery_id: 2, src: '/images/milkyway-over-barrenjoey.jpg', location: 'Australia', category: 'astro', favourite: 'no', width: 3, height: 4},
    {id: 59, gallery_id: 4, src: '/images/barrenjoey-sunset.jpg', location: 'Australia', category: 'landscape', favourite: 'no', width: 4, height: 3},
    {id: 60, gallery_id: 4, src: '/images/sunset-barrenjoey.jpg', location: 'Australia', category: 'landscape', favourite: 'yes', width: 4, height: 3},
    {id: 61, gallery_id: 1, src: '/images/starfish-at-muriwai.jpg', location: 'New Zealand', category: 'landscape', favourite: 'yes', width: 3, height: 4},
    {id: 62, gallery_id: 1, src: '/images/bioluminescence-at-muriwai.jpg', location: 'New Zealand', category: 'landscape', favourite: 'no', width: 4, height: 2},
    {id: 63, gallery_id: 1, src: '/images/tongariro.jpg', location: 'New Zealand', category: 'landscape', favourite: 'no', width: 4, height: 2},
    {id: 64, gallery_id: 1, src: '/images/pink-mountains.jpg', location: 'New Zealand', category: 'landscape', favourite: 'yes', width: 4, height: 3},
    {id: 65, gallery_id: 6, src: '/images/mt-ngauruhoe.jpg', location: 'New Zealand', category: 'landscape', favourite: 'no', width: 4, height: 3},
    {id: 66, gallery_id: 5, src: '/images/gannet.jpg', location: 'New Zealand', category: 'Wildlife', favourite: 'no', width: 4, height: 3},
    {id: 67, gallery_id: 1, src: '/images/mission-bay.jpg', location: 'New Zealand', category: 'Landscape', favourite: 'no', width: 4, height: 3},
    {id: 68, gallery_id: 6, src: '/images/kloster-neuendorf.jpg', location: 'Germany', category: 'Black & White', favourite: 'yes', width: 4, height: 3},
    {id: 69, gallery_id: 6, src: '/images/tasman-lake.jpg', location: 'New Zealand', category: 'Black & White', favourite: 'no', width: 4, height: 2},
    {id: 70, gallery_id: 1, src: '/images/mt-cook.jpg', location: 'New Zealand', category: 'Landscape', favourite: 'no', width: 4, height: 3},
    {id: 71, gallery_id: 3, src: '/images/vivid-opera-house.jpg', location: 'Australia', category: 'Cityscape', favourite: 'no', width: 4, height: 3},
    {id: 72, gallery_id: 3, src: '/images/vivid-sydney.jpg', location: 'Australia', category: 'Cityscape', favourite: 'no', width: 4, height: 3},
    {id: 73, gallery_id: 3, src: '/images/vivid-sydney-cbd.jpg', location: 'Australia', category: 'Cityscape', favourite: 'no', width: 4, height: 3},
    {id: 74, gallery_id: 3, src: '/images/vivid-opera.jpg', location: 'Australia', category: 'Cityscape', favourite: 'no', width: 4, height: 3},
    {id: 75, gallery_id: 3, src: '/images/sunset-in-paris.jpg', location: 'France', category: 'Cityscape', favourite: 'no', width: 4, height: 3},
    {id: 76, gallery_id: 3, src: '/images/sunset-at-the-louvre.jpg', location: 'France', category: 'Cityscape', favourite: 'no', width: 4, height: 3},
    {id: 77, gallery_id: 3, src: '/images/eiffel-tower.jpg', location: 'France', category: 'Cityscape', favourite: 'yes', width: 4, height: 3},
    {id: 78, gallery_id: 3, src: '/images/paris.jpg', location: 'France', category: 'Cityscape', favourite: 'no', width: 4, height: 3},
    {id: 79, gallery_id: 6, src: '/images/tornau.jpg', location: 'Germany', category: 'Black & White', favourite: 'no', width: 4, height: 3},
    {id: 80, gallery_id: 4, src: '/images/kata-tjuta.jpg', location: 'Australia', category: 'Landscape', favourite: 'no', width: 4, height: 3},
    {id: 81, gallery_id: 4, src: '/images/morning-light.jpg', location: 'Australia', category: 'Landscape', favourite: 'no', width: 4, height: 3},
    {id: 82, gallery_id: 2, src: '/images/milkyway-trees.jpg', location: 'Australia', category: 'Astro', favourite: 'no', width: 3, height: 4},
    {id: 83, gallery_id: 4, src: '/images/red-soil.jpg', location: 'Australia', category: 'Landscape', favourite: 'no', width: 4, height: 3},
    {id: 84, gallery_id: 4, src: '/images/uluru.jpg', location: 'Australia', category: 'Landscape', favourite: 'no', width: 4, height: 3},
    {id: 85, gallery_id: 4, src: '/images/port-stephens.jpg', location: 'Australia', category: 'Landscape', favourite: 'no', width: 4, height: 3},
    {id: 86, gallery_id: 4, src: '/images/ebor-falls.jpg', location: 'Australia', category: 'Landscape', favourite: 'no', width: 3, height: 4},
    {id: 87, gallery_id: 4, src: '/images/woolgoolga-sunrise.jpg', location: 'Australia', category: 'Landscape', favourite: 'no', width: 4, height: 3},
    {id: 88, gallery_id: 3, src: '/images/canberra.jpg', location: 'Australia', category: 'Cityscape', favourite: 'no', width: 4, height: 3},
    {id: 89, gallery_id: 5, src: '/images/bee.jpg', location: 'Australia', category: 'Wildlife', favourite: 'yes', width: 3, height: 3},
    {id: 91, gallery_id: 5, src: '/images/leaf-curling-spider.jpg', location: 'Australia', category: 'Wildlife', favourite: 'no', width: 4, height: 3},
    {id: 92, gallery_id: 5, src: '/images/common-garden-skink.jpg', location: 'Australia', category: 'Wildlife', favourite: 'no', width: 4, height: 3},
    {id: 93, gallery_id: 5, src: '/images/striped-marsh-frogs.jpg', location: 'Australia', category: 'Wildlife', favourite: 'no', width: 4, height: 3},
    {id: 94, gallery_id: 1, src: '/images/patiti-point-sunrise.jpg', location: 'New Zealand', category: 'Landscape', favourite: 'no', width: 4, height: 3},
    {id: 95, gallery_id: 1, src: '/images/patiti-point.jpg', location: 'New Zealand', category: 'Landscape', favourite: 'no', width: 4, height: 3},
    {id: 96, gallery_id: 1, src: '/images/patiti-point-morning.jpg', location: 'New Zealand', category: 'Landscape', favourite: 'no', width: 4, height: 3},
    {id: 98, gallery_id: 5, src: '/images/eastern-koel.jpg', location: 'Australia', category: 'Wildlife', favourite: 'no', width: 4, height: 3},
    {id: 99, gallery_id: 5, src: '/images/rainbow-lorikeets.jpg', location: 'Australia', category: 'Wildlife', favourite: 'no', width: 3, height: 4},
    {id: 100, gallery_id: 5, src: '/images/pelicans.jpg', location: 'Australia', category: 'Wildlife', favourite: 'no', width: 3, height: 4},
    {id: 101, gallery_id: 4, src: '/images/red-newcastle-sunrise.jpg', location: 'Australia', category: 'Landscape', favourite: 'no', width: 4, height: 3},
    {id: 102, gallery_id: 4, src: '/images/nobbys-lighthouse.jpg', location: 'Australia', category: 'Landscape', favourite: 'no', width: 4, height: 3},
    {id: 103, gallery_id: 4, src: '/images/byron-bay-lighthouse.jpg', location: 'Australia', category: 'Landscape', favourite: 'no', width: 4, height: 3},
    {id: 104, gallery_id: 4, src: '/images/little-bay.jpg', location: 'Australia', category: 'Wildlife', favourite: 'no', width: 4, height: 3},
    {id: 105, gallery_id: 4, src: '/images/bent.jpg', location: 'Australia', category: 'Landscape', favourite: 'no', width: 4, height: 3},
    {id: 106, gallery_id: 4, src: '/images/kings-canyon-trees.jpg', location: 'Australia', category: 'Landscape', favourite: 'no', width: 4, height: 3},
    {id: 107, gallery_id: 4, src: '/images/kings-canyon-clouds.jpg', location: 'Australia', category: 'Landscape', favourite: 'no', width: 4, height: 3},
    {id: 108, gallery_id: 4, src: '/images/blue-mountains-view.jpg', location: 'Australia', category: 'Wildlife', favourite: 'no', width: 4, height: 3}
    ]);
  });
};
