
exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('photo_details').del()
    .then(function () {
      // Inserts seed entries
      return knex('photo_details').insert([
        {id: 1, photo_id: 1, language_id: 1, title: 'Habour Bridge in Sydney', description: ''},
        {id: 2, photo_id: 1, language_id: 2, title: 'Habour Bridge in Sydney', description: ''},
        {id: 3, photo_id: 2, language_id: 1, title: 'McLaren Falls', description: ''},
        {id: 4, photo_id: 2, language_id: 2, title: 'McLaren Falls', description: ''},
        {id: 5, photo_id: 3, language_id: 1, title: 'White Island', description: ''},
        {id: 6, photo_id: 3, language_id: 2, title: 'White Island', description: ''},
        {id: 7, photo_id: 4, language_id: 1, title: 'Auckland New Years', description: ''},
        {id: 8, photo_id: 5, language_id: 1, title: 'Harbour Bridge View', description: ''},
        {id: 9, photo_id: 6, language_id: 1, title: 'Darling Harbour Fireworks', description: ''},
        {id: 10, photo_id: 7, language_id: 1, title: 'New Years Fireworks in Auckland', description: ''},
        {id: 11, photo_id: 8, language_id: 1, title: 'Muriwai', description: ''},
        {id: 12, photo_id: 9, language_id: 1, title: 'Anawhata', description: ''},
        {id: 13, photo_id: 10, language_id: 1, title: 'Milkyway over Bethells', description: ''},
        {id: 14, photo_id: 11, language_id: 1, title: 'Bethells', description: ''},
        {id: 15, photo_id: 12, language_id: 1, title: 'Pakiri', description: ''},
        {id: 16, photo_id: 13, language_id: 1, title: 'Whatipu', description: ''},
        {id: 17, photo_id: 14, language_id: 1, title: 'Milkyway over Whatipu', description: ''},
        {id: 18,photo_id: 15, language_id: 1, title: 'Blue Mountains', description: ''},
        {id: 19, photo_id: 17, language_id: 1, title: 'Pink Clouds', description: ''},
        {id: 26, photo_id: 23, language_id: 1, title: 'Harbour Bridge', description: ''},
        {id: 21, photo_id: 18, language_id: 1, title: 'Rainy Gold Coast',  description: ''},
        {id: 22, photo_id: 19, language_id: 1, title: 'Milkyway over the Fields of Light', description: ''},
        {id: 23, photo_id: 20, language_id: 1, title: 'Milkyway over Uluru', description: ''},
        {id: 24, photo_id: 21, language_id: 1, title: 'Ghostly Tree', description: ''},
        {id: 25, photo_id: 22, language_id: 1, title: 'Desolate', description: ''},
        {id: 20, photo_id: 16, language_id: 1, title: 'Good morning, Sydney', description: ''},
        {id: 27, photo_id: 24, language_id: 1, title: 'City Views', description: ''},
        {id: 28, photo_id: 25, language_id: 1, title: 'Natural Fireworks', description: ''},
        {id: 29, photo_id: 26, language_id: 1, title: 'Bridge View', description: ''},
        {id: 30, photo_id: 27, language_id: 1, title: 'Gold Coast View', description: ''},
        {id: 31, photo_id: 28, language_id: 1, title: 'Rainbow Parikeet', description: ''},
        {id: 32, photo_id: 29, language_id: 1, title: 'Sydney Harbour', description: ''},
        {id: 33, photo_id: 30, language_id: 1, title: 'Sydney Harbour', description: ''},
        {id: 34, photo_id: 31, language_id: 1, title: 'Smokey Gold Coast Sunrise', description: ''},
        {id: 35, photo_id: 32, language_id: 1, title: 'Pink Gold Coast Sunset', description: ''},
        {id: 36, photo_id: 33, language_id: 1, title: 'Sydney Sails', description: ''},
        {id: 37, photo_id: 34, language_id: 1, title: 'Sydney Park View', description: ''},
        {id: 38, photo_id: 35, language_id: 1, title: 'Gold Coast Storm', description: ''},
        {id: 39, photo_id: 36, language_id: 1, title: 'Opera House Sunrise', description: ''},
        {id: 40, photo_id: 37, language_id: 1, title: 'Storm over Sydney', description: ''},
        {id: 41, photo_id: 38, language_id: 1, title: 'Smokey Morning', description: ''},
        {id: 42, photo_id: 39, language_id: 1, title: 'Gold Coast Blues', description: ''},
        {id: 43, photo_id: 40, language_id: 1, title: 'Auckland Fireworks', description: ''},
        {id: 44, photo_id: 41, language_id: 1, title: 'Auckland in Pink', description: ''},
        {id: 45, photo_id: 42, language_id: 1, title: 'Auckland City Lights', description: ''},
        {id: 46, photo_id: 43, language_id: 1, title: 'Fireworks in Auckland', description: ''},
        {id: 47, photo_id: 44, language_id: 1, title: 'Moon over Melbourne', description: ''},
        {id: 48, photo_id: 45, language_id: 1, title: 'Mt Eden', description: ''},
        {id: 49, photo_id: 46, language_id: 1, title: 'Spaghetti Junction', description: ''},
        {id: 50, photo_id: 47, language_id: 1, title: 'Wellington CBD', description: ''},
        {id: 51, photo_id: 48, language_id: 1, title: 'Westhaven', description: ''}
      ]);
    });
};
